### ISSUE TITLE
Wazuh API randomly responding with false agent information

### ISSUE THREAD

**Issue by 32bitbradley** [wazuh/wazuh-api#466]
As part of our registration process, we do a check to see if the agent name already exists. 
to do this we query the following: 

`GET /agents/name/{{agent_name}}`

If this returns error:1701 to say the agent doesn't exist then we use the API to register the agent with the following. 

```
POST /agents
{
  name: "{{agent_name}}",
  ip: "any"
}
```

Since deploying this solution we have found that sometimes the first query will respond to say that the agent doesn't exist but then when we register we will get the response
"Agent with this name already exists" 

When this happens the only workaround that we can find is to restart the wazuh API as it will keep having the same behaviour until restarted. 

This type of behaviour also happens later with our install script where

We register the agent and then wait 30 seconds before checking to see if the agent has connected. 

and then apply groups to the agent. 

Sometimes it makes it through all these checks and then when applying groups the API will say that the agent doesn't exist again this will keep erroring until the API is restarted

**Comment by davidjiglesias** [comment]
Hello @32bitbradley, I will be glad to try and help you with this problem. In order to better understand the issue, could you please provide the Wazuh and Wazuh-API version you are using?

Best regards,

David I.

**Comment by 32bitbradley** [comment]
Hi @davidjiglesias Thanks for getting back to me :)

We use Wazuh 3.10.2 on Centos 7.7

```
[root@xxx ~]# rpm -qa wazuh-manager
wazuh-manager-3.10.2-1.x86_64
[root@xxx  ~]# rpm -qa wazuh-api
wazuh-api-3.10.2-1.x86_64
[root@xxx  ~]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[root@xxx  ~]#
```

**Comment by davidjiglesias** [comment]
Would it be possible to check the installation script to better understand the exact process?

**Comment by 32bitbradley** [comment]
Hi @davidjiglesias Apologies for the delay.

We use Ansible for agent deployment. This playbook will:
* Get the type of OS
* Install Wazuh agent-based off the OS
* Register the agent using the Wazuh API <-- Mentioned Issue occurring here
* Apply the linking keys to the agent
* After 30 seconds wait, checks to see if the agent is connected.
* If connected, applies desired agent groups for centralised config

**Registration playbook**

```yml
#Checks for if the agents are in
- name: Check if agent already exists
  delegate_to: localhost 
  uri:
    force_basic_auth: true
    user: "{{ wazuh_api_username }}"
    password: "{{ wazuh_api_password }}"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
    url: https://{{URL}}/agents/name/{{ agent_name }}
  register: response_json

#Helps with diagnosing faults occuring during this section
- name: Print the output of previous check
  debug:
    var: response_json

#If previous check fails then add the agent to Wazuh 
- name: Add agent to Wazuh
  delegate_to: localhost
  uri:
    force_basic_auth: true
    user: "{{ wazuh_api_username }}"
    password: "{{ wazuh_api_password }}"
    method: POST
    body_format: json
    return_content: yes
    status_code: 200
    validate_certs: no
    url: https://{{URL}}/agents
    body:
      name: "{{ agent_name }}"
      ip: "any"
  register: add_agent_result
  failed_when: add_agent_result.json.error > 0
  when: 
    - response_json.json.error == 1701

#Pull agent key

- name: Retrieve agent key for existing agent
  delegate_to: localhost
  uri:
    force_basic_auth: true
    user: "{{ wazuh_api_username }}"
    password: "{{ wazuh_api_password }}"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
    url: "https://{{URL}}/agents/{{ response_json.json.data.id }}/key"
  register: agent_key_result
  failed_when: agent_key_result.json.error > 0
  when: 
    - response_json.json.error == 0
```
