### ISSUE TITLE
  Settings. Wazuh API throws socket hang up

### ISSUE THREAD

**Issue by crazyhandpuppet** [wazuh/wazuh-API#69]
I've installed Wazuh onto Ubuntu 16.04.4.  Most of it has gone pretty well up until logging into the browser and adding the API.  There are 4 things to enter:  Username, password, address, and port.  No matter what username and password I use, as long as the address and port are correct, I get "Settings. Wazuh API throws socket hang up".  If I put the wrong port I get "Settings. Wrong Wazuh API port, please check it and try again" so it appears there is communication.  I've reset the password so I know the credentials are correct.

What do I need to do to figure this out?

Thanks in advance.

**Comment by crazyhandpuppet** [comment]
Ack.  I forgot to make the URL https instead of http.  It's connecting now.  You can close or remove this.

**Comment by CODE-REaD** [comment]
Thank you @crazyhandpuppet, for leaving this comment intact.  More precisely, after following instructions at https://documentation.wazuh.com/3.11/installation-guide/securing_api.html#securing-api, the location that needed to be changed from `http` to `https` was in `/usr/share/kibana/plugins/wazuh/wazuh.yml`:

```
#-------------------------------- API entries -----------------------------------
#The following configuration is the default structure to define an API entry.
#
#hosts:
#  - <id>:
#     url: http(s)://<url>
#     port: <port>
#     user: <user>
#     password: <password>

hosts:
  - default:
      url: https://localhost          <---
      port: 55000
      user: myUser
      password: myPass

```
